# Generated by Django 4.2.25 on 2026-01-21 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_blogpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, help_text='Certificate image or thumbnail', null=True, upload_to='achievements/')),
                ('video', models.FileField(blank=True, help_text='Short demo video', null=True, upload_to='achievements/videos/')),
                ('is_video', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='BlogPost',
        ),
    ]
