# Generated by Django 4.2.25 on 2026-01-21 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_achievement_delete_blogpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement',
            name='image',
        ),
        migrations.AddField(
            model_name='achievement',
            name='file',
            field=models.FileField(blank=True, help_text='Certificate file (Image or PDF)', null=True, upload_to='achievements/'),
        ),
    ]
