# Generated by Django 4.2.25 on 2026-01-21 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_achievement_image_achievement_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='video',
            field=models.FileField(blank=True, help_text='Project demo video', null=True, upload_to='projects/videos/'),
        ),
    ]
