# Generated by Django 4.2.5 on 2026-05-29 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_project_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('Frontend', 'Frontend'), ('Backend', 'Backend'), ('AI/ML', 'AI / ML'), ('Tools', 'Tools'), ('Other', 'Other')], max_length=50),
        ),
    ]
